### ISSUE TITLE
Sengled Element Classic (A60) not working with plugin

### ISSUE THREAD

**Issue by pakoR** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#99] opened 2019-03-29 20:09 UTC
If I am right the Sengled Element Classic device (A60) listed as compatible with the plugin corresponds to the model E11-G23, I have a few bulbs of this model that are paired without problem in zigbee2mqtt and listed as "Device E11- G23 / E11-G33 ", but the plugin does not seem to create any device in domoticz. Tested updating to last version both zigbee2mqtt and the plugin.

**Comment by stas-demydiuk** [comment] 2019-03-31 08:09
@pakoR could you please enable debug mode for the plugin and provide your log output from plugin and zigbee2mqtt

**Comment by pakoR** [comment] 2019-03-31 12:23
2019-03-31 14:10:29.631 (Zigbee2MQTT) onStart called
2019-03-31 14:10:29.631 (Zigbee2MQTT) MqttClient::__init__
2019-03-31 14:10:29.631 (Zigbee2MQTT) MqttClient::open
2019-03-31 14:10:29.847 (Zigbee2MQTT) onConnect called
2019-03-31 14:10:29.848 (Zigbee2MQTT) Connected to MQTT Server: 127.0.0.1:1883
2019-03-31 14:10:29.848 (Zigbee2MQTT) MQTT CLIENT ID: 'Domoticz_1554034229_3220'
2019-03-31 14:10:29.898 (Zigbee2MQTT) MqttClient::subscribe
2019-03-31 14:10:29.949 (Zigbee2MQTT) onMQTTSubscribed
2019-03-31 14:10:29.950 (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/state online
2019-03-31 14:10:29.950 (Zigbee2MQTT) Zigbee2mqtt bridge is online
2019-03-31 14:10:29.950 (Zigbee2MQTT) MqttClient::publish zigbee2mqtt/bridge/config/devices ()
2019-03-31 14:10:29.950 (Zigbee2MQTT) MqttClient::publish zigbee2mqtt/bridge/config/permit_join (true)
2019-03-31 14:10:29.950 (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/config {'log_level': 'info', 'permit_join': True, 'version': '1.2.1', 'coordinator_firmware': 20190223, 'commit': '76d7861'}
2019-03-31 14:10:29.950 (Zigbee2MQTT) Zigbee2mqtt log level is info
2019-03-31 14:10:29.950 (Zigbee2MQTT) Joining new devices is enabled on the zigbee bridge
2019-03-31 14:10:30.002 (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/config/devices
2019-03-31 14:10:30.002 (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/config/permit_join True
2019-03-31 14:10:30.055 (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/log {'type': 'devices', 'message': [{'type': 'Coordinator', 'ieeeAddr': '0x00124b0018ed23d1'}, {'manufId': 4447, 'model': 'CC2530.ROUTER', 'manufName': 'LUMI', 'powerSource': 'Mains (single phase)', 'friendly_name': 'RouterCC2531', 'nwkAddr': 28466, 'type': 'Router', 'modelId': 'lumi.router', 'ieeeAddr': '0x00124b0018ed1a70'}, {'manufId': 4151, 'model': 'WSDCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': 'TPHIV', 'nwkAddr': 53908, 'type': 'EndDevice', 'modelId': 'lumi.weather', 'ieeeAddr': '0x00158d0002ca0a2f'}, {'manufId': 4151, 'model': 'WSDCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': '0x00158d0002c8ef3b', 'nwkAddr': 44855, 'type': 'EndDevice', 'modelId': 'lumi.weather', 'ieeeAddr': '0x00158d0002c8ef3b'}, {'manufId': 4151, 'model': 'RTCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': 'SensorEscaleira', 'nwkAddr': 28300, 'type': 'EndDevice', 'modelId': 'lumi.sensor_motion.aq2', 'ieeeAddr': '0x00158d00029c0146'}, {'manufId': 4151, 'model': 'SJCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': 'SensorInundacionI', 'nwkAddr': 20243, 'type': 'EndDevice', 'modelId': 'lumi.sensor_wleak.aq1', 'ieeeAddr': '0x00158d00024974b0'}, {'manufId': 4448, 'model': 'E11-G23/E11-G33', 'manufName': 'sengled', 'powerSource': 'Unknown', 'friendly_name': '0xb0ce1814030e6736', 'nwkAddr': 36019, 'type': 'EndDevice', 'modelId': 'E11-G23', 'ieeeAddr': '0xb0ce1814030e6736'}, {'manufId': 48042, 'model': 'AB3257001NJ', 'manufName': 'OSRAM', 'powerSource': 'Mains (single phase)', 'friendly_name': 'OsramI', 'nwkAddr': 64356, 'type': 'Router', 'modelId': 'Plug 01', 'ieeeAddr': '0x7cb03eaa0a030419'}, {'manufId': 48042, 'model': 'AB3257001NJ', 'manufName': 'OSRAM', 'powerSource': 'Mains (single phase)', 'friendly_name': 'OsramII', 'nwkAddr': 38630, 'type': 'Router', 'modelId': 'Plug 01', 'ieeeAddr': '0x7cb03eaa0a020d52'}, {'manufId': 4447, 'model': 'ZNLDP12LM', 'manufName': 'LUMI', 'powerSource': 'DC Source', 'friendly_name': 'BombillaI', 'nwkAddr': 14006, 'type': 'Router', 'modelId': 'lumi.light.aqcn02', 'ieeeAddr': '0x00158d0002c6568c'}, {'manufId': 4151, 'model': 'WSDCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': 'TPHI', 'nwkAddr': 16139, 'type': 'EndDevice', 'modelId': 'lumi.weather', 'ieeeAddr': '0x00158d0002ca0a33'}, {'manufId': 4151, 'model': 'WSDCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': 'TPHIII', 'nwkAddr': 63554, 'type': 'EndDevice', 'modelId': 'lumi.weather', 'ieeeAddr': '0x00158d0002ca0a1d'}, {'manufId': 4151, 'model': 'WSDCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': 'TPHV', 'nwkAddr': 65195, 'type': 'EndDevice', 'modelId': 'lumi.weather', 'ieeeAddr': '0x00158d0002fb46b6'}, {'manufId': 48042, 'model': 'AB3257001NJ', 'manufName': 'OSRAM', 'powerSource': 'Mains (single phase)', 'friendly_name': '0x7cb03eaa0a024482', 'nwkAddr': 15177, 'type': 'Router', 'modelId': 'Plug 01', 'ieeeAddr': '0x7cb03eaa0a024482'}, {'manufId': 4151, 'model': 'RTCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': '0x00158d000314ba23', 'nwkAddr': 41432, 'type': 'EndDevice', 'modelId': 'lumi.sensor_motion.aq2', 'ieeeAddr': '0x00158d000314ba23'}, {'manufId': 48042, 'model': 'AB3257001NJ', 'manufName': 'OSRAM', 'powerSource': 'Mains (single phase)', 'friendly_name': '0x7cb03eaa0a02defb', 'nwkAddr': 47767, 'type': 'Router', 'modelId': 'Plug 01', 'ieeeAddr': '0x7cb03eaa0a02defb'}, {'manufId': 4151, 'model': 'WSDCGQ11LM', 'manufName': 'LUMI', 'powerSource': 'Battery', 'friendly_name': '0x00158d0002fb4603', 'nwkAddr': 53319, 'type': 'EndDevice', 'modelId': 'lumi.weather', 'ieeeAddr': '0x00158d0002fb4603'}, {'manufId': 4448, 'model': 'E11-G23/E11-G33', 'manufName': 'sengled', 'powerSource': 'Unknown', 'friendly_name': '0xb0ce1814030e4479', 'nwkAddr': 48199, 'type': 'EndDevice', 'modelId': 'E11-G23', 'ieeeAddr': '0xb0ce1814030e4479'}]}
2019-03-31 14:10:30.055 (Zigbee2MQTT) Received available devices list from bridge
2019-03-31 14:10:30.055 (Zigbee2MQTT) Coordinator address is 0x00124b0018ed23d1
2019-03-31 14:10:30.056 (Zigbee2MQTT) Device CC2530.ROUTER 0x00124b0018ed1a70 (RouterCC2531)
2019-03-31 14:10:30.056 (Zigbee2MQTT) Device WSDCGQ11LM 0x00158d0002ca0a2f (TPHIV)
2019-03-31 14:10:30.057 (Zigbee2MQTT) Device WSDCGQ11LM 0x00158d0002c8ef3b (0x00158d0002c8ef3b)
2019-03-31 14:10:30.068 (Zigbee2MQTT) Device RTCGQ11LM 0x00158d00029c0146 (SensorEscaleira)
2019-03-31 14:10:30.068 (Zigbee2MQTT) Device SJCGQ11LM 0x00158d00024974b0 (SensorInundacionI)
2019-03-31 14:10:30.069 (Zigbee2MQTT) Device E11-G23/E11-G33 0xb0ce1814030e6736 (0xb0ce1814030e6736)
2019-03-31 14:10:30.069 (Zigbee2MQTT) Device AB3257001NJ 0x7cb03eaa0a030419 (OsramI)
2019-03-31 14:10:30.070 (Zigbee2MQTT) Device AB3257001NJ 0x7cb03eaa0a020d52 (OsramII)
2019-03-31 14:10:30.070 (Zigbee2MQTT) Device ZNLDP12LM 0x00158d0002c6568c (BombillaI)
2019-03-31 14:10:30.070 (Zigbee2MQTT) Device WSDCGQ11LM 0x00158d0002ca0a33 (TPHI)
2019-03-31 14:10:30.071 (Zigbee2MQTT) Device WSDCGQ11LM 0x00158d0002ca0a1d (TPHIII)
2019-03-31 14:10:30.072 (Zigbee2MQTT) Device WSDCGQ11LM 0x00158d0002fb46b6 (TPHV)
2019-03-31 14:10:30.073 (Zigbee2MQTT) Device AB3257001NJ 0x7cb03eaa0a024482 (0x7cb03eaa0a024482)
2019-03-31 14:10:30.074 (Zigbee2MQTT) Device RTCGQ11LM 0x00158d000314ba23 (0x00158d000314ba23)
2019-03-31 14:10:30.075 (Zigbee2MQTT) Device AB3257001NJ 0x7cb03eaa0a02defb (0x7cb03eaa0a02defb)
2019-03-31 14:10:30.075 (Zigbee2MQTT) Device WSDCGQ11LM 0x00158d0002fb4603 (0x00158d0002fb4603)
2019-03-31 14:10:30.077 (Zigbee2MQTT) Device E11-G23/E11-G33 0xb0ce1814030e4479 (0xb0ce1814030e4479)
2019-03-31 14:10:30.077 (Zigbee2MQTT) MqttClient::subscribe
2019-03-31 14:10:30.128 (Zigbee2MQTT) onMQTTSubscribed
2019-03-31 14:10:30.179 (Zigbee2MQTT) MQTT message: zigbee2mqtt/bridge/config {'log_level': 'info', 'permit_join': True, 'version': '1.2.1', 'coordinator_firmware': 20190223, 'commit': '76d7861'}
2019-03-31 14:10:30.179 (Zigbee2MQTT) Zigbee2mqtt log level is info
2019-03-31 14:10:30.179 (Zigbee2MQTT) Joining new devices is enabled on the zigbee bridge
2019-03-31 14:10:39.199 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:10:39.996 (DarkSky) Temp + Humidity + Baro (Temperatura e Humidade en Ferrol)
2019-03-31 14:10:40.005 (DarkSky) Wind (Vento Ferrol)
2019-03-31 14:10:40.012 (DarkSky) UV (Indice UV Ferrol)
2019-03-31 14:10:40.021 (DarkSky) Rain (Choiva Ferrol)
2019-03-31 14:10:40.028 (DarkSky) General/Visibility (Visibilidade)
2019-03-31 14:10:40.034 (DarkSky) General/Custom Sensor (Ozono Ferrol)
2019-03-31 14:11:41.291 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:11:51.284 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:12:01.307 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:12:11.282 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:12:21.306 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:12:31.285 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:12:36.400 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0x00158d000314ba23 {'battery': 97, 'linkquality': 39, 'illuminance': 97, 'voltage': 2995, 'occupancy': False}
2019-03-31 14:12:41.324 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:12:46.488 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0x00158d000314ba23 {'battery': 97, 'linkquality': 36, 'illuminance': 98, 'voltage': 2995, 'occupancy': False}
2019-03-31 14:12:46.551 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0x00158d000314ba23 {'battery': 97, 'linkquality': 39, 'illuminance': 98, 'voltage': 2995, 'occupancy': True}
2019-03-31 14:12:49.928 (Zigbee2MQTT) MQTT message: zigbee2mqtt/SensorEscaleira {'battery': 100, 'linkquality': 63, 'illuminance': 36, 'voltage': 3005, 'occupancy': False}
2019-03-31 14:12:51.294 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:13:01.318 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:13:11.293 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:13:21.317 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:13:31.340 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:13:41.313 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:13:51.337 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:14:01.309 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:14:11.331 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:14:16.493 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0x00158d000314ba23 {'battery': 97, 'linkquality': 39, 'illuminance': 98, 'voltage': 2995, 'occupancy': False}
2019-03-31 14:14:21.332 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:14:24.891 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0xb0ce1814030e4479 {'linkquality': 110, 'state': 'ON', 'brightness': 255}
2019-03-31 14:14:24.891 (Zigbee2MQTT) Unsupported zigbee device type with model "E11-G23/E11-G33"
2019-03-31 14:14:25.092 (Zigbee2MQTT) MQTT message: zigbee2mqtt/0xb0ce1814030e4479 {'linkquality': 107, 'state': 'ON', 'brightness': 255}
2019-03-31 14:14:25.093 (Zigbee2MQTT) Unsupported zigbee device type with model "E11-G23/E11-G33"
2019-03-31 14:14:31.357 (Zigbee2MQTT) MqttClient::ping
2019-03-31 14:14:41.332 (Zigbee2MQTT) MqttClient::ping

**Comment by pakoR** [comment] 2019-03-31 12:31
mar 31 14:28:30 DomoticzPi npm[1678]:   zigbee2mqtt:warn 2019-3-31 14:28:30 Message without device!
mar 31 14:28:35 DomoticzPi npm[1678]:   zigbee2mqtt:warn 2019-3-31 14:28:35 Device with modelID 'undefined' is not supported.
mar 31 14:28:35 DomoticzPi npm[1678]:   zigbee2mqtt:warn 2019-3-31 14:28:35 Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
mar 31 14:28:36 DomoticzPi npm[1678]:   zigbee2mqtt:info 2019-3-31 14:28:36 MQTT publish: topic 'zigbee2mqtt/0xb0ce1814030e4479', payload '{"state":"ON","linkquality":113,"brightness":255}'
mar 31 14:28:36 DomoticzPi npm[1678]:   zigbee2mqtt:info 2019-3-31 14:28:36 MQTT publish: topic 'zigbee2mqtt/0xb0ce1814030e4479', payload '{"state":"ON","linkquality":110,"brightness":255}'
mar 31 14:28:37 DomoticzPi npm[1678]:   zigbee2mqtt:info 2019-3-31 14:28:37 Device incoming...
mar 31 14:28:37 DomoticzPi npm[1678]:   zigbee2mqtt:info 2019-3-31 14:28:37 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"device incoming"}'

**Comment by pakoR** [comment] 2019-03-31 12:32
The problem is on zigbee2mqtt?

**Comment by stas-demydiuk** [comment] 2019-03-31 15:49
The problem is in `Device with modelID 'undefined' is not supported`. It sometimes happens that during including device into zigbee network it doesn't send model identifier. I would suggest to remove device from network and pair it one more time. Or wait until zigbee network do self-update and resolve issue.

**Comment by pakoR** [comment] 2019-03-31 20:03
Thanks stas, I have those 2 sengled devices connecting the zigbee network for 2 weeks before I open this issue, and now I tried removing all entries of those 2 devices from zigbee2mqtt/data/database.db and repaired again with no luck for 4 times getting the same "Device with modelID 'undefined' is not supported".
I guess should open an issue in zigbee2mqtt.

**Comment by stas-demydiuk** [comment] 2019-04-07 07:46
@pakoR I'll close the issue here for now, please reopen it if some fix will be required in plugin itself

**Closed by stas-demydiuk** 2019-04-07 07:46 UTC

**Comment by pakoR** [comment] 2019-11-17 12:15
Finally I got the Sengled Element Classic (A60) working, but I needed to change in `__init__.py` the line 
`'E11-G23': DimmableBulbAdapter,         # Sengled Element Classic (A60)` to `'E11-G23/E11-G33': DimmableBulbAdapter,         # Sengled Element Classic (A60)` and then the device is created and working.
