### ISSUE TITLE
Issue with Ikea bulbs with cold/warm light.

### ISSUE THREAD

**Issue by dobber81** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#576] opened 2021-02-10 19:22 UTC
**Issue description**
Error messages for Ikea light bulbs with cold/warm light.
I think the messages started maybe 2 weeks ago. About the same time as the "effect" switches were introduced.

**Additional information**
Zigbee2MQTT version: v.1.17.1-dev
Python version: 3.7.3
Domoticz version: 2020.2 (build 12934)
Plugin version:  latest build 10/2-21

**Logs**
2021-02-10 20:15:18.299 Error: Python Plugin System: (Zigbee2MQTT) Matbord: can not process numeric item "color_temp_startup"
2021-02-10 20:15:18.305 Error: Python Plugin System: (Zigbee2MQTT) Trappa: can not process numeric item "color_temp_startup"

**Comment by stas-demydiuk** [comment] 2021-02-10 20:13
Duplicate of #569

**Closed by stas-demydiuk** 2021-02-10 20:13 UTC
