### ISSUE TITLE
Timers with zigbee2mqtt RGBWW Dimmer

### ISSUE THREAD

**Issue by devrosx** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#726] opened 2021-10-08 21:41 UTC
**Issue description**
This is repost (domoticz bug), but noticed that it happens only on zigbee2mqtt device (on dummy device is OK) so it might be in plugin or python framework.
Described here:
https://github.com/domoticz/domoticz/issues/4959
Sorry if its not zigbee2mqtt bug....

thanks for your great plugin

**Additional information**
Zigbee2MQTT version:
Python version: 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]
Domoticz version: latest 
Plugin version: latest

**Comment by odelma** [comment] 2021-10-15 05:24
> ...in domoticz RGB and WW switch are always Off and color wheel is in the middle. I can turn on light set color etc but it always reverts to off in domoticz interface (light stays as set). 

I can confirm this. It has been like this since many months so this is not an issue related to latest changes (at lest that is what I would say). Even though it is something I have used to live with, it would be nice to get fixed.

**Comment by stas-demydiuk** [comment] 2021-12-25 09:56
Closing the issue as it looks like the same as #714. Should be fixed with the latest plugin version

**Closed by stas-demydiuk** 2021-12-25 09:56 UTC
