### ISSUE TITLE
can not process feature type "composite" and process numeric item in philips hue in domoticz

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#593] opened 2021-02-19 21:53 UTC
Dear friend @stas-demydiuk ,

When i start zigbe2mqtt i get these errors in my 4 philips hue bulbs

```
2021-02-19 22:36:32.015 Error: Python Plugin System: (zigbe2mqtt) Philips hue1: can not process numeric item "color_temp_startup"
2021-02-19 22:36:32.015 Error: Python Plugin System: (zigbe2mqtt) Philips hue1: can not process feature type "composite"
2021-02-19 22:36:32.016 Error: Python Plugin System: (zigbe2mqtt) Philips hue2: can not process numeric item "color_temp_startup"
2021-02-19 22:36:32.016 Error: Python Plugin System: (zigbe2mqtt) Philips hue2: can not process feature type "composite"
2021-02-19 22:36:32.016 Error: Python Plugin System: (zigbe2mqtt) Philips hue3: can not process numeric item "color_temp_startup"
2021-02-19 22:36:32.016 Error: Python Plugin System: (zigbe2mqtt) Philips hue3: can not process feature type "composite"
2021-02-19 22:36:32.017 Error: Python Plugin System: (zigbe2mqtt) Philips hue4: can not process numeric item "color_temp_startup"
2021-02-19 22:36:32.017 Error: Python Plugin System: (zigbe2mqtt) Philips hue4: can not process feature type "composite"
```
Before the error i can read this zigbe2mqtt messages:

```
2021-02-19 22:51:22.813 Python Plugin System: (zigbe2mqtt) {"access": 7, "description": "Color temperature after cold power on of this light", "name": "color_temp_startup", "presets": [{"description": "Coolest temperature supported", "name": "coolest", "value": 150}, {"description": "Cool temperature (250 mireds / 4000 Kelvin)", "name": "cool", "value": 250}, {"description": "Neutral temperature (370 mireds / 2700 Kelvin)", "name": "neutral", "value": 370}, {"description": "Warm temperature (454 mireds / 2200 Kelvin)", "name": "warm", "value": 454}, {"description": "Warmest temperature supported", "name": "warmest", "value": 500}, {"description": "Restore previous color_temp on cold power on", "name": "previous", "value": 65535}], "property": "color_temp_startup", "type": "numeric", "unit": "mired", "value_max": 500, "value_min": 150}
2021-02-19 22:51:22.814 Python Plugin System: (zigbe2mqtt) {"description": "Color of this light expressed as hue/saturation", "features": [{"access": 7, "name": "hue", "property": "hue", "type": "numeric"}, {"access": 7, "name": "saturation", "property": "saturation", "type": "numeric"}], "name": "color_hs", "property": "color", "type": "composite"}
2021-02-19 22:51:22.814 Python Plugin System: (zigbe2mqtt) {"access": 7, "description": "Color temperature after cold power on of this light", "name": "color_temp_startup", "presets": [{"description": "Coolest temperature supported", "name": "coolest", "value": 150}, {"description": "Cool temperature (250 mireds / 4000 Kelvin)", "name": "cool", "value": 250}, {"description": "Neutral temperature (370 mireds / 2700 Kelvin)", "name": "neutral", "value": 370}, {"description": "Warm temperature (454 mireds / 2200 Kelvin)", "name": "warm", "value": 454}, {"description": "Warmest temperature supported", "name": "warmest", "value": 500}, {"description": "Restore previous color_temp on cold power on", "name": "previous", "value": 65535}], "property": "color_temp_startup", "type": "numeric", "unit": "mired", "value_max": 500, "value_min": 150}
2021-02-19 22:51:22.815 Python Plugin System: (zigbe2mqtt) {"description": "Color of this light expressed as hue/saturation", "features": [{"access": 7, "name": "hue", "property": "hue", "type": "numeric"}, {"access": 7, "name": "saturation", "property": "saturation", "type": "numeric"}], "name": "color_hs", "property": "color", "type": "composite"}
2021-02-19 22:51:22.815 Python Plugin System: (zigbe2mqtt) {"access": 7, "description": "Color temperature after cold power on of this light", "name": "color_temp_startup", "presets": [{"description": "Coolest temperature supported", "name": "coolest", "value": 150}, {"description": "Cool temperature (250 mireds / 4000 Kelvin)", "name": "cool", "value": 250}, {"description": "Neutral temperature (370 mireds / 2700 Kelvin)", "name": "neutral", "value": 370}, {"description": "Warm temperature (454 mireds / 2200 Kelvin)", "name": "warm", "value": 454}, {"description": "Warmest temperature supported", "name": "warmest", "value": 500}, {"description": "Restore previous color_temp on cold power on", "name": "previous", "value": 65535}], "property": "color_temp_startup", "type": "numeric", "unit": "mired", "value_max": 500, "value_min": 150}
2021-02-19 22:51:22.815 Python Plugin System: (zigbe2mqtt) {"description": "Color of this light expressed as hue/saturation", "features": [{"access": 7, "name": "hue", "property": "hue", "type": "numeric"}, {"access": 7, "name": "saturation", "property": "saturation", "type": "numeric"}], "name": "color_hs", "property": "color", "type": "composite"}
2021-02-19 22:51:22.823 Python Plugin System: (zigbe2mqtt) {"access": 7, "description": "Color temperature after cold power on of this light", "name": "color_temp_startup", "presets": [{"description": "Coolest temperature supported", "name": "coolest", "value": 150}, {"description": "Cool temperature (250 mireds / 4000 Kelvin)", "name": "cool", "value": 250}, {"description": "Neutral temperature (370 mireds / 2700 Kelvin)", "name": "neutral", "value": 370}, {"description": "Warm temperature (454 mireds / 2200 Kelvin)", "name": "warm", "value": 454}, {"description": "Warmest temperature supported", "name": "warmest", "value": 500}, {"description": "Restore previous color_temp on cold power on", "name": "previous", "value": 65535}], "property": "color_temp_startup", "type": "numeric", "unit": "mired", "value_max": 500, "value_min": 150}
2021-02-19 22:51:22.825 Python Plugin System: (zigbe2mqtt) {"description": "Color of this light expressed as hue/saturation", "features": [{"access": 7, "name": "hue", "property": "hue", "type": "numeric"}, {"access": 7, "name": "saturation", "property": "saturation", "type": "numeric"}], "name": "color_hs", "property": "color", "type": "composite"}
2021-02-19 22:51:22.831 Python Plugin System: (zigbe2mqtt) Zigbee2mqtt log level is info

```

Could you include this feature in the plugin?

Thanks in advanced

Best regards

**Comment by stas-demydiuk** [comment] 2021-03-21 09:13
Duplicate of #569

**Closed by stas-demydiuk** 2021-03-21 09:13 UTC
Labels: new device
