### ISSUE TITLE
LIDL HG06104A does not have color set in Domoticz

### ISSUE THREAD

**Issue by humphs01** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#585] opened 2021-02-17 00:04 UTC
https://www.zigbee2mqtt.io/devices/HG06104A.html

Device in Domoticz for this LED strip does not have color control. The following devices are created - on/off, brightness, effec and link quality

![image](https://user-images.githubusercontent.com/79176194/108137272-75a2ea00-70b3-11eb-8f64-2fdfaca0fdbd.png)

I noticed the following error in the log - (Zigbee2MQTT)  can not process numeric item "color_temp". I updated to the latest plugin and the error stopped but there was no color control or set in Domoticz

**Comment by devrosx** [comment] 2021-02-22 20:55
same problem here
2021-02-22 21:52:21.772 Error: Python Plugin System: (ZBX) 0x00124b001ee9709a: can not process numeric item "color_temp_startup"

**Comment by stas-demydiuk** [comment] 2021-03-07 20:03
Please enable debug mode and post here full device information from zigbee2mqtt

**Comment by devrosx** [comment] 2021-03-07 20:06
here is... 

2021-03-07 21:05:36.311 Python Plugin System: (ZBX) Debug logging mask set to: PYTHON
2021-03-07 21:05:36.311 Python Plugin System: (ZBX) onStart called
2021-03-07 21:05:36.311 Python Plugin System: (ZBX) Installing plugin custom page...
2021-03-07 21:05:36.311 Python Plugin System: (ZBX) Copying files from /home/pi/domoticz/plugins/zigbee2mqtt/frontend to /home/pi/domoticz/www/templates
2021-03-07 21:05:36.327 Python Plugin System: (ZBX) Installing plugin custom page completed.
2021-03-07 21:05:36.327 Python Plugin System: (ZBX) MqttClient::__init__
2021-03-07 21:05:36.327 Python Plugin System: (ZBX) MqttClient::open
2021-03-07 21:05:36.378 Python Plugin System: (ZBX) onConnect called
2021-03-07 21:05:36.378 Python Plugin System: (ZBX) Connected to MQTT Server: 127.0.0.1:1883
2021-03-07 21:05:36.378 Python Plugin System: (ZBX) MQTT CLIENT ID: 'Domoticz_1615147536_6839'
2021-03-07 21:05:36.428 Python Plugin System: (ZBX) MqttClient::subscribe
2021-03-07 21:05:36.479 Python Plugin System: (ZBX) onMQTTSubscribed
2021-03-07 21:05:36.479 Python Plugin System: (ZBX) Zigbee2mqtt bridge is online
2021-03-07 21:05:36.479 Python Plugin System: (ZBX) MqttClient::publish zigbee2mqtt/bridge/config/groups ()
2021-03-07 21:05:36.479 Python Plugin System: (ZBX) Zigbee2mqtt log level is info
2021-03-07 21:05:36.479 Python Plugin System: (ZBX) Joining new devices is disabled on the zigbee bridge
2021-03-07 21:05:36.481 Python Plugin System: (ZBX) Received available devices list from bridge
2021-03-07 21:05:36.481 Python Plugin System: (ZBX) Coordinator address is 0x00124b00193b1594
2021-03-07 21:05:36.483 Python Plugin System: (ZBX) {"access": 7, "description": "Color temperature after cold power on of this light", "name": "color_temp_startup", "presets": [{"description": "Coolest temperature supported", "name": "coolest", "value": 150}, {"description": "Cool temperature (250 mireds / 4000 Kelvin)", "name": "cool", "value": 250}, {"description": "Neutral temperature (370 mireds / 2700 Kelvin)", "name": "neutral", "value": 370}, {"description": "Warm temperature (454 mireds / 2200 Kelvin)", "name": "warm", "value": 454}, {"description": "Warmest temperature supported", "name": "warmest", "value": 500}, {"description": "Restore previous color_temp on cold power on", "name": "previous", "value": 65535}], "property": "color_temp_startup", "type": "numeric", "unit": "mired", "value_max": 500, "value_min": 150}
2021-03-07 21:05:36.483 Python Plugin System: (ZBX) MqttClient::subscribe
2021-03-07 21:05:36.534 Python Plugin System: (ZBX) onMQTTSubscribed
2021-03-07 21:05:36.535 Python Plugin System: (ZBX) Received groups list from bridge
2021-03-07 21:05:36.097 Status: Python Plugin System: (ZBX) Stopping threads.
2021-03-07 21:05:36.097 Status: Python Plugin System: (ZBX) Stopped.
2021-03-07 21:05:36.097 Status: Python Plugin System: (ZBX) Started.
2021-03-07 21:05:36.304 Status: Python Plugin System: (ZBX) Entering work loop.
2021-03-07 21:05:36.304 Status: Python Plugin System: (ZBX) Initialized version 3.0.0
2021-03-07 21:05:36.483 Error: Python Plugin System: (ZBX) 0x00124b001ee9709a: can not process numeric item "color_temp_startup"

**Comment by stas-demydiuk** [comment] 2021-03-21 09:14
Looks like it is duplicate of #569

**Closed by stas-demydiuk** 2021-03-21 09:14 UTC

**Comment by devrosx** [comment] 2021-03-21 09:44
thanks my error message is still visible with latest changes...

`2021-03-21 10:41:21.357 Error: Python Plugin System: (ZBX) Disconnected from MQTT Server: 127.0.0.1:1883
2021-03-21 10:41:21.850 Error: Python Plugin System: (ZBX) 0x00124b001ee9709a: can not process numeric item "color_temp_startup"`

Zigbee USB Mini LED Controller RGB+CCT 
GL-MC-001

it has 3 devices
Color Switch
General (with quality signal)
Light/Switch
--

but in domoticz all works fine






--
