### ISSUE TITLE
Xiaomi WXKG11LM - triple action

### ISSUE THREAD

**Issue by elpaul** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#536] opened 2020-12-30 09:14 UTC
Good morning.
I noticed a problem with the Xiaomi WXKG11LM button. More specifically with the action "triple".
After pressing the button three times in the domoticz logs the following will appear: `(Zigbee) Unable to find selector switch level for value "triple"`
All other functions (single, double, quadruple, hold) work fine.
Where to look for the cause?
![image](https://user-images.githubusercontent.com/9497662/103341554-8d80c900-4a87-11eb-96fd-46e83a8a24fd.png)

**Additional information**
Zigbee2MQTT version: 1.16.2
Python version: 3.7.3
Domoticz version: 2020.2
Plugin version: last

**Comment by Lokysek** [comment] 2021-01-01 10:07
Hi all,
i have the same problem with 

WXKG01LM | MiJia wireless switch

Single, double, quadruple, hold and release works fine,
but tripple is not :-(

**Comment by gurbyz** [comment] 2021-01-23 17:25
I couldn't get the triple click to work either. But I noticed that in the documentation [here](https://www.zigbee2mqtt.io/devices/WXKG11LM.html) the action is spelled as `tripple` (with 2 `p`'s). I didn't see `triple` nor `tripple` in my mqtt logs. `single` and `double` where fine and I could see them in the logs.

Maybe somewhere in the code the `tripple` and `triple` spelling gets mixed up and the action gets lost?

**Comment by stas-demydiuk** [comment] 2021-09-04 12:10
Can someone please test if the issue is still valid?

**Comment by gurbyz** [comment] 2021-09-04 12:34
My part of the issue still is. Same as it was January 23th.

**Comment by stas-demydiuk** [comment] 2021-09-12 08:56
Closing the ticket as it is zigbee2mqtt issue itself not the plugin one, hopefully will be fixed once

**Closed by stas-demydiuk** 2021-09-12 08:56 UTC
Labels: bug
