### ISSUE TITLE
Error message from generic_device.lua

### ISSUE THREAD

**Issue by snorro80** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#713] opened 2021-09-17 15:00 UTC
**Issue description**
Plugin version 3.1.0 creates error messages in generic_device.lua line 67 (error: attempt to index a nil value).
[Topic](https://www.domoticz.com/forum/viewtopic.php?f=59&t=36994) on Domoticz forum.

**Additional information**
Zigbee2MQTT version: v.1.21.1 (zStack12 20190608)
Python version: 2.7.16
Domoticz version: 2021.1 (build 13499)
Plugin version: Zigbee2MQTT Plugin (v. 3.1.0-beta)

**Logs**
`2021-09-13 12:56:31.895 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
`

**Comment by arjanvanleent** [comment] 2021-09-17 22:04
Same problem already reported but closed.
This is a log of a clean Domoticz installation with only the Zigbee pluging installed

> 2021-09-17 23:48:22.359 Sunrise: 07:22:00 SunSet: 19:54:00
2021-09-17 23:48:22.359 Day length: 12:32:00 Sun at south: 13:38:00
2021-09-17 23:48:22.359 Civil twilight start: 06:48:00 Civil twilight end: 20:28:00
2021-09-17 23:48:22.359 Nautical twilight start: 06:08:00 Nautical twilight end: 21:08:00
2021-09-17 23:48:22.359 Astronomical twilight start: 05:25:00 Astronomical twilight end: 21:51:00
2021-09-17 23:48:22.077 Status: Domoticz V2021.1 (build 13499) (c)2012-2021 GizMoCuz
2021-09-17 23:48:22.078 Status: Build Hash: eee4de721, Date: 2021-09-16 07:36:53
2021-09-17 23:48:22.078 Status: Startup Path: /home/pi/domoticz/
2021-09-17 23:48:23.292 Active notification Subsystems: (0/13)
2021-09-17 23:48:23.361 Starting shared server on: :::6144
2021-09-17 23:48:23.255 Status: PluginSystem: Started, Python version '3.7.3'.
2021-09-17 23:48:23.334 Status: WebServer(HTTP) started on address: :: with port 8080
2021-09-17 23:48:23.357 Status: WebServer(SSL) started on address: :: with port 443
2021-09-17 23:48:23.362 Status: RxQueue: queue worker started...
2021-09-17 23:48:23.362 Status: TCPServer: shared server started...
2021-09-17 23:48:25.364 Status: NotificationSystem: thread started...
2021-09-17 23:48:25.364 Status: EventSystem: reset all events...
2021-09-17 23:48:26.364 Status: MQTT Test: Connecting to 192.168.1.98:1883
2021-09-17 23:48:26.402 Status: EventSystem: reset all device statuses...
2021-09-17 23:48:26.526 Status: Python EventSystem: Initializing event module.
2021-09-17 23:48:26.526 Status: EventSystem: Started
2021-09-17 23:48:26.526 Status: EventSystem: Queue thread started...
2021-09-17 23:48:26.364 Error: MQTT Test: Failed to start, return code: 14 (Check IP/Port)
2021-09-17 23:49:18.715 Status: MQTT Test: Connecting to 192.168.1.98:1883
2021-09-17 23:49:18.917 Status: MQTT Test: connected to: 192.168.1.98:1883
2021-09-17 23:49:34.324 ZigBee 2 MQTT hardware started.
2021-09-17 23:49:34.323 Status: ZigBee 2 MQTT: (ZigBee 2 MQTT) Entering work loop.
2021-09-17 23:49:34.324 Status: ZigBee 2 MQTT: (ZigBee 2 MQTT) Started.
2021-09-17 23:49:35.225 ZigBee 2 MQTT: (ZigBee 2 MQTT) Installing plugin custom page...
2021-09-17 23:49:35.347 ZigBee 2 MQTT: (ZigBee 2 MQTT) Installing plugin custom page completed.
2021-09-17 23:49:35.407 ZigBee 2 MQTT: (ZigBee 2 MQTT) Connected to MQTT Server: 192.168.1.98:1883
2021-09-17 23:49:35.509 ZigBee 2 MQTT: (ZigBee 2 MQTT) Zigbee2mqtt bridge is online
2021-09-17 23:49:35.517 ZigBee 2 MQTT: (ZigBee 2 MQTT) Received available devices list from bridge
2021-09-17 23:49:35.222 Status: ZigBee 2 MQTT: (ZigBee 2 MQTT) Initialized version 3.1.0-beta
2021-09-17 23:49:41.073 ZigBee 2 MQTT: (ZigBee 2 MQTT) Joining new devices is disabled on the zigbee bridge
2021-09-17 23:49:41.220 ZigBee 2 MQTT: (ZigBee 2 MQTT) Received groups list from bridge
2021-09-17 23:49:41.220 ZigBee 2 MQTT: (ZigBee 2 MQTT) Group links_achter_dimmer
2021-09-17 23:49:41.275 ZigBee 2 MQTT: (ZigBee 2 MQTT) Group links_voor_dimmer
2021-09-17 23:49:41.330 ZigBee 2 MQTT: (ZigBee 2 MQTT) Group rechts_achter_dimmer
2021-09-17 23:49:41.385 ZigBee 2 MQTT: (ZigBee 2 MQTT) Group slaapkamer_dimmer
2021-09-17 23:49:41.441 ZigBee 2 MQTT: (ZigBee 2 MQTT) Group woonkamer_dimmer
2021-09-17 23:49:41.497 ZigBee 2 MQTT: (ZigBee 2 MQTT) Group Tuin Verlichting_dimmer
2021-09-17 23:56:25.486 Status: EventSystem: reset all device statuses...
2021-09-17 23:57:09.883 Status: EventSystem: reset all events...
2021-09-17 23:57:09.885 Status: dzVents: Write file: /home/pi/domoticz/scripts/dzVents/generated_scripts/Koelkast.lua
2021-09-17 23:57:14.855 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:57:15.065 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:57:27.563 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:58:00.557 Status: dzVents: Info: ------ Start internal script: Koelkast:, trigger: "every 1 minutes"
2021-09-17 23:58:00.580 Status: dzVents: Info: ------ Finished Koelkast
2021-09-17 23:58:00.580 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2021-09-17 23:58:14.820 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:00.578 Status: dzVents: Info: ------ Start internal script: Koelkast:, trigger: "every 1 minutes"
2021-09-17 23:59:00.609 Status: dzVents: Info: ------ Finished Koelkast
2021-09-17 23:59:00.610 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2021-09-17 23:59:04.813 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:04.965 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.038 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.118 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.194 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.270 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.343 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.427 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.503 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-17 23:59:05.573 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-18 00:00:00.603 Status: dzVents: Info: ------ Start internal script: Koelkast:, trigger: "every 1 minutes"
2021-09-18 00:00:00.631 Status: dzVents: Info: ------ Finished Koelkast
2021-09-18 00:00:00.631 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2021-09-18 00:00:01.079 Sunrise: 07:23:00 SunSet: 19:52:00
2021-09-18 00:00:01.079 Day length: 12:28:00 Sun at south: 13:38:00
2021-09-18 00:00:01.079 Civil twilight start: 06:50:00 Civil twilight end: 20:25:00
2021-09-18 00:00:01.079 Nautical twilight start: 06:09:00 Nautical twilight end: 21:06:00
2021-09-18 00:00:01.079 Astronomical twilight start: 05:27:00 Astronomical twilight end: 21:48:00
2021-09-18 00:00:01.079 Status: EventSystem: reset all events...
2021-09-18 00:00:01.080 Status: dzVents: Write file: /home/pi/domoticz/scripts/dzVents/generated_scripts/Koelkast.lua
2021-09-18 00:00:07.679 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-18 00:00:25.416 Status: User: Admin (IP: 192.168.1.100) initiated a switch command (66/midden_slaapkamer (Light)/On)
2021-09-18 00:00:27.232 Status: User: Admin (IP: 192.168.1.100) initiated a switch command (66/midden_slaapkamer (Light)/Set Level)
2021-09-18 00:00:28.504 Status: User: Admin (IP: 192.168.1.100) initiated a switch command (66/midden_slaapkamer (Light)/Off)
2021-09-18 00:01:00.606 Status: dzVents: Info: ------ Start internal script: Koelkast:, trigger: "every 1 minutes"
2021-09-18 00:01:00.636 Status: dzVents: Info: ------ Finished Koelkast
2021-09-18 00:01:00.636 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2021-09-18 00:01:01.854 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-18 00:01:01.977 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-18 00:01:02.057 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-18 00:01:02.128 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-18 00:01:02.199 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua: ...oticz/dzVents/runtime/device-adapters/generic_device.lua:67: attempt to index a nil value (field '_')
2021-09-18 00:02:00.125 Status: dzVents: Info: ------ Start internal script: Koelkast:, trigger: "every 1 minutes"
2021-09-18 00:02:00.158 Status: dzVents: Info: ------ Finished Koelkast
2021-09-18 00:02:00.159 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua

**Comment by stas-demydiuk** [comment] 2021-10-02 15:29
As I see from the forum thread, there is nothing that could be fixed on the plugin side, so I'm going to close this issue. If you think that the root cause is in switching from Domtocz to DomticzEx framework feel free to report this issue in Domoticz

**Closed by stas-demydiuk** 2021-10-02 15:29 UTC
