### ISSUE TITLE
miboxer-fut039z issue in domoticz

### ISSUE THREAD

**Issue by acaonweb** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#747] opened 2021-12-07 19:59 UTC
**Issue description**
No rgb control in domoticz

**Additional information**
Zigbee2MQTT version: Zigbee2MQTT version
1.22.0 commit: b3e9afaf

Python version:3.7.3
Domoticz version:2021.1 build 13872
Plugin version:3.1.0-beta

I've bought this rgb led strip controller

https://www.zigbee2mqtt.io/devices/FUT039Z.html#miboxer-fut039z

Zigbee2mqtt discover it and expose everything is expected to be exposed

![image](https://user-images.githubusercontent.com/22882393/145097346-b96ce767-8b41-4f9b-bbb4-f4b2fb17a25e.png)

Domoticz instead give only to choose this devices, 

![image](https://user-images.githubusercontent.com/22882393/145097541-5997e3b7-c1f9-4d73-a4e2-4a5a64ee700e.png)

I can't see rgb device

What I have to do?

Thanks
Fabrizio

**Comment by acaonweb** [comment] 2021-12-09 20:18
No help?

**Comment by acaonweb** [comment] 2021-12-13 15:38
let me know if is ok this behaviour, thanks

**Comment by acaonweb** [comment] 2021-12-19 10:19
i confirm that in domoticz I can't control Rob values. 
in zigbe2mqtt I can control colors but not in domoticz, I can't control anything

**Comment by acaonweb** [comment] 2021-12-23 09:20
up

**Comment by stas-demydiuk** [comment] 2021-12-25 09:38
Could you please provide JSON with features that your device exposes

**Comment by acaonweb** [comment] 2021-12-26 12:16
{
    "color": {
        "h": 34,
        "hue": 28,
        "s": 83,
        "saturation": 90
    },
    "color_mode": "color_temp",
    "color_power_on_behavior": "initial",
    "color_temp": 440,
    "do_not_disturb": false,
    "linkquality": 81,
    "state": "OFF"
}

**Comment by acaonweb** [comment] 2021-12-26 12:19
<img width="1522" alt="Schermata 2021-12-26 alle 13 18 55" src="https://user-images.githubusercontent.com/22882393/147407799-e4c0d95c-6dda-4343-a8e7-2a8433591b94.png">

**Comment by acaonweb** [comment] 2022-01-02 15:09
Any news?

**Comment by stas-demydiuk** [comment] 2022-01-05 21:46
Looks like the root cause is the same as for #620, this `hs` color system is not supported yet by the plugin

**Comment by stas-demydiuk** [comment] 2022-01-05 21:47
Closing the ticket in favor of #620

**Closed by stas-demydiuk** 2022-01-05 21:47 UTC
