### ISSUE TITLE
Off delay in Domoticz doesn’t work

### ISSUE THREAD

**Issue by gielie** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#794] opened 2022-03-01 13:19 UTC
**Issue description**
When i use the option “off delay” in Domoticz the switch should switch off after the given time when it is turned on. This has always worked fine until last update of the plugin (don’t know the number). The on delay works fine and other switches then zigbee2mqtt also works fine, like hue switches or z-wave switches, it is only the Zigbee that doesn’t work. 

**Additional information**
Zigbee2MQTT version: 1.23.0-dev
Python version: python 3
Domoticz version: 2022.1 stable
Plugin version: 3.1.0-beta

**Logs**
Don’t have any log or error, don’t know how to debug this.

**Comment by jvrrr** [comment] 2022-03-15 19:28
Same issue here

**Comment by Docteur-No** [comment] 2022-03-23 10:47
Same issue here so, Please, answer us !!

**Comment by SargonofAssyria** [comment] 2022-03-30 07:51
I am using:
Version: 2022.1 (build 14285)
Build Hash: 7cac83ba6
Compile Date: 2022-03-17 08:46:22
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
**With plugin version 3.0.1 from 13 jun 2021**
and the 'off delay' is working as it should.

**Comment by Docteur-No** [comment] 2022-03-30 08:58
Many thanks SargonofAssyria for your feedback
It seems it is the 3.1.0 beta who has an issue.
I think I'll try to go back to an older version (after a backup ;-))

**Comment by gielie** [comment] 2022-03-31 10:18
I can confirm 3.01 is working thanks to SargonofAssyria. 
I also can confirm that this (https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/325 Switch to DomoticzEx Framework) is the one that breaks the off delay. 

Can this be fixed?

**Comment by odelma** [comment] 2022-04-14 09:56
Is this a problem in the plugin or in the framework? There was a lot of issues with the framework initially (like it did not trigger devicechanged if the value that was set was the same as current - making push buttons useless). If it is in the framework, then it should be raised as an issue in Domoticz repo.

**Comment by gielie** [comment] 2022-04-15 07:02
> Is this a problem in the plugin or in the framework? There were a lot of issues with the framework initially (like it did not trigger devicechanged if the value that was set was the same as current - making push buttons useless). If it is in the framework, then it should be raised as an issue in Domoticz repo.

That’s a valid question, I don’t know and I don’t know how to debug this. 

one thing is the Zigbee plugin is the only plugin I have with this problem, others like hue, Bluetooth or zwave don’t show this behaviour.

**Comment by odelma** [comment] 2022-04-15 07:25
The framework is only for python plugins afaik. If the other python plugins produce this behavior then I’d say it is the framework.

**Comment by stas-demydiuk** [comment] 2022-04-30 15:31
Closing the issue as it isn't related to the plugin and caused by Domoticz itself, feel free to raise the ticket in the Domoticz repository

**Closed by stas-demydiuk** 2022-04-30 15:31 UTC
