### ISSUE TITLE
Webui not vissible and z2m working fine

### ISSUE THREAD

**Issue by Dylantje** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#430] opened 2020-10-04 07:58 UTC
Latest beta Domoticz
Latets version plugin.
Running for months ok.
After a update, do not wich...
I see no webui any more

Did reinstall the plugin more times, no luck @ all

![image](https://user-images.githubusercontent.com/5214969/95010229-e4f9cf00-0627-11eb-813e-d3bd3cb301f8.png)

Also did remove the cookies etc ets
Other browser.
Only not working

![image](https://user-images.githubusercontent.com/5214969/95010238-065abb00-0628-11eb-9e5b-60c5fbf74b6b.png)

The ystem z2m is working fast and fine.
Only the webui..
So i cannot change names etc

**Comment by salopette** [comment] 2020-10-04 08:33
Yes, something broke after the Domoticz update.

As long as it has not been repaired, you can use z2m's Web Gui.

https://www.zigbee2mqtt.io/information/frontend.html

https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/429

**Comment by stas-demydiuk** [comment] 2020-10-07 06:57
The issue is fixed in the latest plugin version

**Closed by stas-demydiuk** 2020-10-07 06:57 UTC
