### ISSUE TITLE
Upgraded plugin now Custom/Zigbee2mqtt page does not render

### ISSUE THREAD

**Issue by alan-rpi** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#671] opened 2021-07-13 18:28 UTC
**Issue description**
Running under Docker on Rasp Pi4. PC is Windows 7 ESU. Browser FireFox 78.11.0esr (64-bit)

First upgraded Zigbee2mqtt and after problems with Custom/Zigbee2mqtt page does not render completely: Always "Loading....." and no version info and no "Allow new zigbee devices to join"  + none of the Switches work, I upgraded the plugin but problems remain.

I normally use Firefox but it is the same in Opera and Chrome. The new Zigbee2MQTT web front end is working OK. 

Here is a screen shot with the Chrome Inspect where it shows no html for the v.xxxxxxxxx  [ ] Allow new zigbee devices to join

![Domotixcz custom zigbee2mqtt Chrome](https://user-images.githubusercontent.com/25422008/125502592-c2ef1b0d-8707-4b87-8c87-2b66f6addd80.jpg)

You will notice that the page title says Zigbee2Mqtt**2** as I altered the frontend/zigbee2mqtt.html file to validate the plugin was being used.

I asked for help on the Domoticz forum  https://www.domoticz.com/forum/posting.php?mode=reply&f=47&t=36635  and was advised to try an older version:

`root@e8e0c1e0f2ae:/# cd /src/domoticz/plugins/zigbee2mqtt
root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# git reset --hard b708fc4
HEAD is now at b708fc4 fix renaming of devices
root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# `
and restart the system. But its the same. 

**Additional information**
Domoticz V2020.2 (build 12705)
Zigbee2MQTT version 1.20.0 (commit #41b67fd)
zigbee-herdsman (0.13.117)
plugin ## v3.0 from # Changelog file  - cannot find any build info
Python 2.7.16
Python 3.7.3

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

Domoticz log
`021-07-13 11:53:26.364 Sunrise: 05:05:00 SunSet: 21:21:00
2021-07-13 11:53:26.365 Day length: 16:15:00 Sun at south: 13:13:00
2021-07-13 11:53:26.365 Civil twilight start: 04:20:00 Civil twilight end: 22:06:00
2021-07-13 11:53:26.365 Nautical twilight start: 03:14:00 Nautical twilight end: 23:12:00
2021-07-13 11:53:26.365 There is no astronomical twilight in the space of 24 hours
2021-07-13 11:53:26.458 Active notification Subsystems: email, fcm, telegram (3/13)
2021-07-13 11:53:26.462 Starting shared server on: 0.0.0.0:6144
2021-07-13 11:53:26.351 Status: Domoticz V2020.2 (build 12705) (c)2012-2020 GizMoCuz
2021-07-13 11:53:26.351 Status: Build Hash: d05c1201b-modified, Date: 2020-11-25 08:40:24
2021-07-13 11:53:26.351 Status: Startup Path: /src/domoticz/
2021-07-13 11:53:26.454 Status: PluginSystem: Started, Python version '3.7.3'.
2021-07-13 11:53:26.460 Status: WebServer(HTTP) started on address: 0.0.0.0 with port 8080
2021-07-13 11:53:26.463 Status: TCPServer: shared server started...
2021-07-13 11:53:26.463 Status: RxQueue: queue worker started...
2021-07-13 11:53:28.513 Status: Sysfs GPIO: Startup - polling:no interrupts:yes debounce:50msec inputs:11 outputs:6
2021-07-13 11:53:28.514 Status: (Zigbee2MQTT Dongle) Started.
2021-07-13 11:53:28.514 Status: EventSystem: reset all events...
2021-07-13 11:53:28.514 Status: NotificationSystem: thread started...
2021-07-13 11:53:28.514 Status: Sysfs GPIO: Edge detection started
2021-07-13 11:53:28.515 Status: EventSystem: reset all device statuses...
2021-07-13 11:53:28.622 Status: Python EventSystem: Initalizing event module.
2021-07-13 11:53:28.623 Status: EventSystem: Started
2021-07-13 11:53:28.623 Status: EventSystem: Queue thread started...
2021-07-13 11:53:28.871 Status: PluginSystem: Entering work loop.
2021-07-13 11:53:29.132 (Zigbee2MQTT Dongle) Installing plugin custom page...
2021-07-13 11:53:29.160 (Zigbee2MQTT Dongle) Installing plugin custom page completed.
2021-07-13 11:53:29.210 (Zigbee2MQTT Dongle) Connected to MQTT Server: 192.168.1.42:1883
2021-07-13 11:53:29.311 (Zigbee2MQTT Dongle) Zigbee2mqtt bridge is online
2021-07-13 11:53:29.315 (Zigbee2MQTT Dongle) Received available devices list from bridge
2021-07-13 11:53:29.315 (Zigbee2MQTT Dongle) 0x00124b002235dd6e: device definiton not found, skipping...
2021-07-13 11:53:29.315 (Zigbee2MQTT Dongle) Joining new devices is disabled on the zigbee bridge
2021-07-13 11:53:29.130 Status: (Zigbee2MQTT Dongle) Entering work loop.
2021-07-13 11:53:29.131 Status: (Zigbee2MQTT Dongle) Initialized version 3.0.0
2021-07-13 11:53:29.514 Status: MQTT: Connecting to 192.168.1.42:1883
2021-07-13 11:53:29.716 Status: MQTT: connected to: 192.168.1.42:1883
2021-07-13 11:53:29.917 Status: MQTT: Subscribed `

The Domoticz log in Docker has a few more lines: 
`2021-07-13 11:53:29.315  (Zigbee2MQTT Dongle) Joining new devices is disabled on the zigbee bridge
2021-07-13 11:53:29.514  Status: MQTT: Connecting to 192.168.1.42:1883
2021-07-13 11:53:29.716  Status: MQTT: connected to: 192.168.1.42:1883
2021-07-13 11:53:29.917  Status: MQTT: Subscribed
2021-07-13 11:53:36.165  Status: Incoming connection from: 192.168.1.15`

Plugin logs: - I just searched for log files

`root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# tail .git/logs/HEAD   
0000000000000000000000000000000000000000 ea6a170f65185778a7d4ee954f0499dce5449229 root <root@e8e0c1e0f2ae.(none)> 1626124019 +0100        clone: from https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git
ea6a170f65185778a7d4ee954f0499dce5449229 b708fc4fa82277ce1767ccecacc7dfaaf7738642 root <root@e8e0c1e0f2ae.(none)> 1626173552 +0100        reset: moving to b708fc4
root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# cat .git/logs/HEAD 
0000000000000000000000000000000000000000 ea6a170f65185778a7d4ee954f0499dce5449229 root <root@e8e0c1e0f2ae.(none)> 1626124019 +0100        clone: from https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git
ea6a170f65185778a7d4ee954f0499dce5449229 b708fc4fa82277ce1767ccecacc7dfaaf7738642 root <root@e8e0c1e0f2ae.(none)> 1626173552 +0100        reset: moving to b708fc4`

`root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# cat .git/logs/refs/heads/master 
0000000000000000000000000000000000000000 ea6a170f65185778a7d4ee954f0499dce5449229 root <root@e8e0c1e0f2ae.(none)> 1626124019 +0100        clone: from https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git
ea6a170f65185778a7d4ee954f0499dce5449229 b708fc4fa82277ce1767ccecacc7dfaaf7738642 root <root@e8e0c1e0f2ae.(none)> 1626173552 +0100        reset: moving to b708fc4
root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# `

`root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# cat .git/logs/refs/remotes/origin/HEAD   
0000000000000000000000000000000000000000 ea6a170f65185778a7d4ee954f0499dce5449229 root <root@e8e0c1e0f2ae.(none)> 1626124019 +0100        clone: from https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git
root@e8e0c1e0f2ae:/src/domoticz/plugins/zigbee2mqtt# `

Sorry, no preview on github so cannot say how the above will render.

Thanks
Alan
UK

**Comment by bessie1984** [comment] 2021-07-23 13:37
I got the exact same problem, I started from scratch. 
- installed the lastest RPI lite image (buster)
- installed the latest domoticz version using the instructions from the wiki
- installed the latest zigbee2mqtt using the instructions of the zigbee2mqtt website
- installed the latest version of the plugin (domoticz-zigbee2mqtt-plugin)

The same problem as alan-rpi writes. I went back to an older version of the plugin, same problem. Eventually, i got it working again with version 1.17.1 of Zigbee2mqtt and version 0.20 of the plugin. But my curiosity pushed me to update the plugin again (version 3.0) and the result was that it was still worked. So it has something to do with the lastest version of zigbee2mqtt.

**Comment by Oleg-Sob** [comment] 2021-08-11 07:27
I, too, do not display devices on the Zigbee2Mqtt tab, the download is in progress all the time and nothing happens. ZigBee devices are added and work fine, you can see them on the device tab. Devices are not displayed on the Zigbee2Mqtt tab. Tell me what the problem is.

![222](https://user-images.githubusercontent.com/71137109/128987623-39c65f92-4e42-4373-bc6a-89bbcfa8f0ec.PNG)

**Comment by Oleg-Sob** [comment] 2021-08-13 07:51
Help solve the problem, devices are not displayed on the Zigbee2Mqtt tab and the network map does not work. They are in devices.

**Comment by eigthyeight** [comment] 2021-08-17 20:15
I have the same issue....
Installed from scratch with lastest versions
RPI with RPI OS lite, 
zigbee2mqtt 1.21
plugin 3.0.0
Slaesh's CC2652RB stick 

just a loading screen in the plugin tab....

logs:

 2021-08-17 21:56:41.921 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/logging {'level': 'info', 'message': 'Connected to MQTT server'}
2021-08-17 21:56:41.921 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/logging {'level': 'info', 'message': "MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'"}
2021-08-17 21:56:41.921 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/state online
2021-08-17 21:56:41.921 Zigbeemqtt: (Zigbeemqtt) Zigbee2mqtt bridge is online
2021-08-17 21:56:41.921 Zigbeemqtt: (Zigbeemqtt) MqttClient::publish zigbee2mqtt/bridge/config/groups ()
2021-08-17 21:56:41.971 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/config/groups
2021-08-17 21:56:42.074 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/info {'commit': '70891eec', 'config': {'advanced': {'adapter_concurrent': None, 'adapter_delay': None, 'availability_blacklist': [], 'availability_blocklist': [], 'availability_passlist': [], 'availability_timeout': 0, 'availability_whitelist': [], 'cache_state': True, 'cache_state_persistent': True, 'cache_state_send_on_startup': True, 'channel': 11, 'elapsed': False, 'ext_pan_id': [221, 221, 221, 221, 221, 221, 221, 221], 'homeassistant_discovery_topic': 'homeassistant', 'homeassistant_legacy_entity_attributes': False, 'homeassistant_legacy_triggers': True, 'homeassistant_status_topic': 'hass/status', 'last_seen': 'disable', 'legacy_api': False, 'log_directory': '/opt/zigbee2mqtt/data/log/%TIMESTAMP%', 'log_file': 'log.txt', 'log_level': 'info', 'log_output': ['console', 'file'], 'log_rotation': True, 'log_symlink_current': False, 'log_syslog': {}, 'pan_id': 6754, 'report': False, 'soft_reset_timeout': 0, 'timestamp_format': 'YYYY-MM-DD HH:mm:ss'}, 'ban': [], 'blocklist': [], 'device_options': {'legacy': False}, 'devices': {}, 'experimental': {'output': 'json'}, 'external_converters': [], 'groups': {}, 'homeassistant': False, 'map_options': {'graphviz': {'colors': {'fill': {'coordinator': '#e04e5d', 'enddevice': '#fff8ce', 'router': '#4ea3e0'}, 'font': {'coordinator': '#ffffff', 'enddevice': '#000000', 'router': '#ffffff'}, 'line': {'active': '#009900', 'inactive': '#994444'}}}}, 'mqtt': {'base_topic': 'zigbee2mqtt', 'force_disable_retain': False, 'include_device_information': False, 'server': 'mqtt://localhost', 'user': 'mqtt'}, 'ota': {'disable_automatic_update_check': False, 'update_check_interval': 1440}, 'passlist': [], 'permit_join': True, 'serial': {'disable_led': False, 'port': '/dev/ttyUSB0'}, 'whitelist': []}, 'config_schema': {'definitions': {'device': {'properties': {'debounce': {'description': 'Debounces messages of this device', 'title': 'Debounce', 'type': 'number'}, 'debounce_ignore': {'description': 'Protects unique payload values of specified payload properties from overriding within debounce time', 'examples': ['action'], 'items': {'type': 'string'}, 'title': 'Ignore debounce', 'type': 'array'}, 'filtered_attributes': {'description': 'Filter attributes from publish payload.', 'examples': ['temperature', 'battery', 'action'], 'items': {'type': 'string'}, 'title': 'Filtered publish attributes', 'type': 'array'}, 'filtered_optimistic': {'description': 'Filter attributes from optimistic publish payload when calling /set. (This has no effect if optimistic is set to false).', 'examples': ['color_mode', 'color_temp', 'color'], 'items': {'type': 'string'}, 'title': 'Filtered optimistic attributes', 'type': 'array'}, 'friendly_name': {'description': 'Used in the MQTT topic of a device. By default this is the device ID', 'readOnly': True, 'title': 'Friendly name', 'type': 'string'}, 'icon': {'description': 'The user-defined device icon for the frontend. It can be a link to an image (not a path to a file) or base64 encoded data URL like: image/svg+xml;base64,PHN2ZyB3aW....R0aD', 'title': 'Icon', 'type': 'string'}, 'optimistic': {'default': True, 'description': 'Publish optimistic state after set', 'title': 'Optimistic', 'type': 'boolean'}, 'qos': {'description': 'QoS level for MQTT messages of this device', 'title': 'QoS', 'type': 'number'}, 'retain': {'description': 'Retain MQTT messages of this device', 'title': 'Retain', 'type': 'boolean'}, 'retention': {'description': 'Sets the MQTT Message Expiry in seconds, Make sure to set mqtt.version to 5', 'title': 'Retention', 'type': 'number'}}, 'required': ['friendly_name'], 'type': 'object'}, 'group': {'properties': {'devices': {'items': {'type': 'string'}, 'type': 'array'}, 'filtered_attributes': {'items': {'type': 'string'}, 'type': 'array'}, 'friendly_name': {'type': 'string'}, 'optimistic': {'type': 'boolean'}, 'qos': {'type': 'number'}, 'retain': {'type': 'boolean'}}, 'required': ['friendly_name'], 'type': 'object'}}, 'properties': {'advanced': {'properties': {'adapter_concurrent': {'description': 'Adapter concurrency (e.g. 2 for CC2531 or 16 for CC26X2R1) (default: null, uses recommended value)', 'requiresRestart': True, 'title': 'Adapter concurrency', 'type': ['number', 'null']}, 'adapter_delay': {'description': 'Adapter delay', 'requiresRestart': True, 'title': 'Adapter delay', 'type': ['number', 'null']}, 'availability_blacklist': {'items': {'type': 'string'}, 'readOnly': True, 'requiresRestart': True, 'title': 'Availability blacklist (deprecated, use availability_blocklist)', 'type': 'array'}, 'availability_blocklist': {'description': 'Prevent devices from being checked for availability', 'items': {'type': 'string'}, 'requiresRestart': True, 'title': 'Availability Blocklist', 'type': 'array'}, 'availability_passlist': {'description': 'Only enable availability check for certain devices', 'items': {'type': 'string'}, 'requiresRestart': True, 'title': 'Availability passlist', 'type': 'array'}, 'availability_timeout': {'default': 0, 'description': 'Availability timeout in seconds when enabled, devices will be checked if they are still online. Only AC powered routers are checked for availability', 'minimum': 0, 'requiresRestart': True, 'title': 'Availability Timeout', 'type': 'number'}, 'availability_whitelist': {'items': {'type': 'string'}, 'readOnly': True, 'requiresRestart': True, 'title': 'Availability whitelist (deprecated, use passlist)', 'type': 'array'}, 'baudrate': {'description': 'Baud rate speed for serial port, this can be anything firmware support but default is 115200 for Z-Stack and EZSP, 38400 for Deconz, however note that some EZSP firmware need 57600', 'examples': [38400, 57600, 115200], 'requiresRestart': True, 'title': 'Baudrate', 'type': 'number'}, 'cache_state': {'default': True, 'description': 'MQTT message payload will contain all attributes, not only changed ones. Has to be true when integrating via Home Assistant', 'title': 'Cache state', 'type': 'boolean'}, 'cache_state_persistent': {'default': True, 'description': 'Persist cached state, only used when cache_state: true', 'title': '
2021-08-17 21:56:42.074 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/devices [{'definition': None, 'endpoints': {'1': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '10': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '11': {'bindings': [], 'clusters': {'input': ['ssIasAce'], 'output': ['ssIasZone', 'ssIasWd']}, 'configured_reportings': []}, '110': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '12': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '13': {'bindings': [], 'clusters': {'input': ['genOta'], 'output': []}, 'configured_reportings': []}, '2': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '242': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '3': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '4': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '47': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '5': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '6': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}, '8': {'bindings': [], 'clusters': {'input': [], 'output': []}, 'configured_reportings': []}}, 'friendly_name': 'Coordinator', 'ieee_address': '0x00124b002298a8c2', 'interview_completed': True, 'interviewing': False, 'network_address': 0, 'supported': False, 'type': 'Coordinator'}]
2021-08-17 21:56:42.074 Zigbeemqtt: (Zigbeemqtt) Received available devices list from bridge
2021-08-17 21:56:42.074 Zigbeemqtt: (Zigbeemqtt) Coordinator address is 0x00124b002298a8c2
2021-08-17 21:56:42.074 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/groups []
2021-08-17 21:56:42.074 Zigbeemqtt: (Zigbeemqtt) MQTT message: zigbee2mqtt/bridge/extensions [] 

anyone got a solution?

**Comment by odelma** [comment] 2021-08-18 09:36
If I remember correct, there were some files changed in the frontend folder. What I did (again - if I remember correctly 😃) is that I removed all the related files in the custom pages folder (where they are copied to) and maybe also in current the frontend folder and then updated the plugin / copied them directly from here. After that I have been able to load the page again.

**Comment by stas-demydiuk** [comment] 2021-09-12 08:58
Closing as duplicate of #686, please post all further discussion there

**Closed by stas-demydiuk** 2021-09-12 08:58 UTC
