### ISSUE TITLE
Plugin zigbee2mqtt doesn't work with bullseye raspbian 11

### ISSUE THREAD

**Issue by kitopopo** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#760] opened 2021-12-30 11:53 UTC
Dear friend,

I have installed zigbee2mqtt in a raspberry pi 3b+ with bullseye but all obtain the following errors: 

```
2021-12-30 12:47:57.049 Error: Zigbee2MQTT: (Zigbee2MQTT) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/zigbee2mqtt/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2021-12-30 12:47:57.049 Error: Zigbee2MQTT: (Zigbee2MQTT) Module Import failed, exception: 'ModuleNotFoundError'
2021-12-30 12:47:57.049 Error: Zigbee2MQTT: (Zigbee2MQTT) Module Import failed: ' Name: DomoticzEx'
2021-12-30 12:47:57.049 Error: Zigbee2MQTT: (Zigbee2MQTT) Error Line details not available.
```

Any solution? thanks in advanced. 

Best regards

**Comment by sammyke007** [comment] 2022-01-05 08:19
Bullseye (11) and Domoticz is a bad combination for now anyway due to Python plugin issues. Please revert to Buster (10) or wait for fixes.

**Comment by stas-demydiuk** [comment] 2022-01-05 21:28
Closing as the issue is not related to the plugin

**Closed by stas-demydiuk** 2022-01-05 21:28 UTC
