### ISSUE TITLE
Error after update to 3.0.0

### ISSUE THREAD

**Issue by cndian** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#647] opened 2021-05-20 19:16 UTC
Hello,

I have updated the Zigbee plugin for domoticz but when I change color of my group spots I get this error;

 2021-05-20 21:12:49.430 Status: setcolbrightnessvalue: ID: 1b9, bri: 51, color: '{m: 3, RGB: ffcd5c, CWWW: 0000, CT: 0}'
2021-05-20 21:12:49.526 Error: Zigbee2mqtt: (Zigbee2mqtt) 'onMessage' failed 'KeyError'.
2021-05-20 21:12:49.526 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 297 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-05-20 21:12:49.527 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 137 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-05-20 21:12:49.527 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2021-05-20 21:12:49.527 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 219 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2021-05-20 21:12:49.527 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 81 in '/home/pi/domoticz/plugins/zigbee2mqtt/groups_manager.py', function handle_mqtt_message
2021-05-20 21:12:49.527 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 64 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handle_mqtt_message
2021-05-20 21:12:49.527 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 65 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function handle_message
2021-05-20 21:12:49.527 Error: Zigbee2mqtt: (Zigbee2mqtt) ----> Line 22 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/base_colortemp_light.py', function get_color_value 

And with startup the zigbee bridge I get this error;

 2021-05-20 21:26:23.378 Error: Zigbee2mqtt: (Zigbee2mqtt) Lamp voor: can not process numeric item "color_temp_startup"
2021-05-20 21:26:23.379 Error: Zigbee2mqtt: (Zigbee2mqtt) Spot keuken 3: can not process numeric item "color_temp_startup"
2021-05-20 21:26:23.379 Error: Zigbee2mqtt: (Zigbee2mqtt) Spot keuken 4: can not process numeric item "color_temp_startup"
2021-05-20 21:26:23.380 Error: Zigbee2mqtt: (Zigbee2mqtt) Spot keuken 1: can not process numeric item "color_temp_startup"
2021-05-20 21:26:23.380 Error: Zigbee2mqtt: (Zigbee2mqtt) Spot keuken 2: can not process numeric item "color_temp_startup"
2021-05-20 21:26:23.382 Error: Zigbee2mqtt: (Zigbee2mqtt) Lamp wc: can not process numeric item "color_temp_startup"
2021-05-20 21:26:23.384 Error: Zigbee2mqtt: (Zigbee2mqtt) 0x0017880109209f82: can not process numeric item "color_temp_startup"
2021-05-20 21:26:23.384 Error: Zigbee2mqtt: (Zigbee2mqtt) 0x00178801085be83e: can not process numeric item "color_temp_startup" 

How does it come? The spots do change color.

Thanks

**Comment by stas-demydiuk** [comment] 2021-05-23 08:37
Duplicate of #569

**Closed by stas-demydiuk** 2021-05-23 08:37 UTC
