### ISSUE TITLE
Domoticz log overflow with zigbee comments

### ISSUE THREAD

**Issue by Tjilie** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#114] opened 2019-05-08 18:20 UTC
**Issue description**
Since tatest update Domoticz log overflow with zigbee comment
**Additional information**
Zigbee2MQTT version:1.3.1
Python version:3.5.3
Domoticz version:4.10693
Plugin version:00.18

**Logs**
Domoticz log look like this, how can I stop this
2019-05-08 20:18:58.631 (Zigbee Gateway) Received available devices list from bridge
2019-05-08 20:18:58.631 (Zigbee Gateway) Device WXKG02LM 0x00158d0002569754 (aqara_ws01)
2019-05-08 20:18:58.632 (Zigbee Gateway) Device MFKZQ01LM 0x00158d00028f419c (aqara_cube)
2019-05-08 20:18:58.632 (Zigbee Gateway) Device WXKG02LM 0x00158d0002fceef7 (aqara_ws02)
2019-05-08 20:18:58.633 (Zigbee Gateway) Device KS-SM001 0x01124b001bae7cd6 (zonoff_01)
2019-05-08 20:18:58.633 (Zigbee Gateway) Device ZNCZ02LM 0x00158d00032d365d (mijia_ps01)
2019-05-08 20:18:58.634 (Zigbee Gateway) Device JTYJ-GD-01LM/BW 0x00158d0002cb06a7 (honeywell_01)
2019-05-08 20:18:58.634 (Zigbee Gateway) Device MCCGQ11LM 0x00158d0003121273 (aqara_ds01)
2019-05-08 20:18:58.635 (Zigbee Gateway) Device MCCGQ11LM 0x00158d000312e39d (aqara_ds02)
2019-05-08 20:18:58.635 (Zigbee Gateway) Device WSDCGQ11LM 0x00158d0002d79082 (aqara_thp02)
2019-05-08 20:18:58.636 (Zigbee Gateway) Device WSDCGQ11LM 0x00158d000303ca09 (aqara_thp01)
2019-05-08 20:18:58.637 (Zigbee Gateway) Device WSDCGQ11LM 0x00158d0003499181 (aqara_thp03)

please how can I stop this

**Comment by stas-demydiuk** [comment] 2019-05-09 11:43
@Tjilie Plugin restart usually helps. It is intermittent issue I cannot regularly reproduce to be able to fix

**Comment by Tjilie** [comment] 2019-05-09 19:11
Within Domoticz wen interface I disabled and update the plugin and after that I enabled and update the plugin. This does not changed the logging. Also I update to the mast recent stable version this make also no differents.

**Comment by Tjilie** [comment] 2019-05-10 06:12
Sorry I accidentally closed issue.

So as I wrote before restart plugin does not help.

When I open the Domoticz outside my home network I don't have this Zigbee log and have only the normal log

**Comment by stas-demydiuk** [comment] 2019-05-10 08:03
Could you please also try to restart your MQTT server

**Comment by Tjilie** [comment] 2019-05-10 09:07
I will do so tomorrow. I planned to make a back-up of my SD-card tomorrow morning.

**Comment by Tjilie** [comment] 2019-05-11 05:12
I restarted my RPI (and cloned Sd-card), update CC2531 USB stick to latest version. 

This also did not help, logging still the same unfortunately

**Comment by Tjilie** [comment] 2019-05-11 08:52
Now most of the switches don't work any more but are connected to broker an visable in log. Only the

**Comment by Tjilie** [comment] 2019-05-18 16:00
@ stas-demydiuk
The Domoticz log still overflow with zigbee comment. What a also see is that my domoticz database is growing big fast. Is this related to each other?

**Comment by stas-demydiuk** [comment] 2019-12-14 10:31
Looks like issue was on Domoticz side, haven't seen this issue for more than 3 months, so will close this issue. Please reopen ticket if will occur again.

**Closed by stas-demydiuk** 2019-12-14 10:31 UTC
